CREATE OR REPLACE PROCEDURE WIDEWORLDIMPORTERSDW.DWH.LOADALLDATAWAREHOUSETABLES()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
CALL dwh.LoadDimCity();
CALL dwh.LoadDimEmployee();
CALL dwh.LoadDimStockItems();
CALL dwh.LoadDimCustomer();
CALL dwh.LoadFactSales();
END';